// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAESSNw07sH7RBqZTOGwlByrdGLwBvXvik',
    appId: '1:436255186322:web:540ac5b6c790e430b3f54b',
    messagingSenderId: '436255186322',
    projectId: 'trucklogix-60b08',
    authDomain: 'trucklogix-60b08.firebaseapp.com',
    storageBucket: 'trucklogix-60b08.firebasestorage.app',
    measurementId: 'G-E1TPLPX76L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-elMzmLhpyPKPj3RoMW6j3zwz8B_Wnhs',
    appId: '1:436255186322:android:159ab7b773178564b3f54b',
    messagingSenderId: '436255186322',
    projectId: 'trucklogix-60b08',
    storageBucket: 'trucklogix-60b08.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBp2sFjhAJrWfvD6WURsNBfVe-ydz6vh7s',
    appId: '1:436255186322:ios:550cf5856f7aa035b3f54b',
    messagingSenderId: '436255186322',
    projectId: 'trucklogix-60b08',
    storageBucket: 'trucklogix-60b08.firebasestorage.app',
    iosBundleId: 'com.example.trucklogix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBp2sFjhAJrWfvD6WURsNBfVe-ydz6vh7s',
    appId: '1:436255186322:ios:550cf5856f7aa035b3f54b',
    messagingSenderId: '436255186322',
    projectId: 'trucklogix-60b08',
    storageBucket: 'trucklogix-60b08.firebasestorage.app',
    iosBundleId: 'com.example.trucklogix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAESSNw07sH7RBqZTOGwlByrdGLwBvXvik',
    appId: '1:436255186322:web:0ad36d6357b563dcb3f54b',
    messagingSenderId: '436255186322',
    projectId: 'trucklogix-60b08',
    authDomain: 'trucklogix-60b08.firebaseapp.com',
    storageBucket: 'trucklogix-60b08.firebasestorage.app',
    measurementId: 'G-9B0Y2ME78X',
  );
}
